@page "/"
@rendermode InteractiveServer
@using SharedService
@inject UserState_Management_Service userStateService
@inject NavigationManager navigator
@inject HttpClient httpClient

<PageTitle>Home</PageTitle>


<h1 class="text-center">Welcome to Todo App</h1>

<div class="form-container" align="center">
    <EditForm Model="user" FormName="UserLogin" class="form-group w-50" OnSubmit="LoginUser">
        <div class="mb-3">
            <label for="username" class="form-label">Username:</label>
            <input class="form-control" type="text" id="username" @bind-value=user.Username placeholder="Enter the Username" required />
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password:</label>
            <input class="form-control" type="password" id="password" @bind-value=user.Password placeholder="Enter the Password" min="8" maxlength="15" required />
        </div>
        <button class="btn btn-primary" type="submit">Submit</button>
    </EditForm>

    @message
</div>

<p class="text-center mt-5">
    Don't Have An Account? 
    <NavLink href="signup">Sign Up</NavLink>
</p>

@code
{
    public class User
    {
        public string Username { get; set; } = "";
        public string Password { get; set; } = "";
    }

    string message = "";
    bool IsValid = false;

    public User user = new();

    private async Task LoginUser()
    {
        try
        {
            var res = await httpClient.GetAsync($"http://localhost:5075/Todo/GetUser?username={user.Username}&password={user.Password}");
            if(res.IsSuccessStatusCode)
            {
                message = await res.Content.ReadAsStringAsync();
                if(navigator != null)
                {
                    userStateService.Username = user.Username;
                    userStateService.IsLoggedIn = true;

                    navigator.NavigateTo("/todo");
                }
            }
            else
            {
                message = "Login Failed. Please check the credentials";
            }
        }
        catch(Exception e)
        {
            message = $"Error Occurred: {e}";
        }
    }
}